### ISSUE TITLE
Invalid package name

### ISSUE THREAD

**Issue by a-bashtannik** [shutterstock/php-shutterstock-api#1]
Hi

Your repository is `shutterstock/php-shutterstock-api` but package name is 'shutterstock/api'.

`composer require shutterstock/php-shutterstock-api` will fail.

You have to rename repository and readme.md or package name.

Now `composer require shutterstock/api` works fine.

**Comment by meishern** [comment]
Thank you. Worked for me.

**Comment by belguinan** [comment]
Thank you

**Comment by behradkhodayar** [comment]
The issue is reported 2 years ago & still existing?!! What do you do there at ShutterStock?!

**Comment by jacobemerick** [comment]
Closed in #2
